#!/usr/bin/env python3
"""Live E2E test for Heima lighting-schedule learning pipeline (P9).

Pipeline tested:
  1. (optional) learning_reset        — wipe all learning data first
  2. real recording check             — toggle light entity → verify LightingRecorderBehavior
                                        captures STATE_CHANGED (requires area_id on room,
                                        set via recover_test_lab_config.py --section lighting_areas)
  3. seed_lighting_events             — inject synthetic events (for _spans_min_weeks gate)
  4. reload config entry              → ProposalEngine.async_run()
  5. sensor + diagnostic check        → lighting_scene_schedule proposal pending
  6. accept proposal                  → options flow reactions/proposals step
  7. verify accepted status           → sensor poll

NOTE: by default this script does NOT reset learning data so it can run safely
after 020_learning_pipeline.py and 030_learning_proposals_diag.py without
destroying presence proposals already generated by those tests.
Use --reset to force a full learning reset before seeding.

Usage:
    python3 scripts/live_tests/060_lighting_schedule.py \\
        --ha-url http://127.0.0.1:8123 \\
        --ha-token <token> \\
        --light-entity light.test_heima_living_main \\
        --room-id living

    # Full reset first (standalone run):
    python3 scripts/live_tests/060_lighting_schedule.py ... --reset
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path
import sys
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lib.ha_client import HAApiError, HAClient


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _to_int(value: Any) -> int:
    raw = str(value or "").strip().lower()
    if raw in {"", "unknown", "unavailable", "none"}:
        return 0
    return int(float(raw))


def _assert(cond: bool, msg: str) -> None:
    if not cond:
        raise AssertionError(msg)


def _proposals_attrs(client: HAClient, entity_id: str) -> dict[str, Any]:
    state = client.get_state(entity_id)
    return dict(state.get("attributes") or {})


def _find_lighting_proposal(attrs: dict[str, Any], status: str = "pending") -> tuple[str, dict] | None:
    """Return (proposal_id, proposal_dict) for first lighting_scene_schedule with given status."""
    for pid, proposal in attrs.items():
        if not isinstance(proposal, dict):
            continue
        if (proposal.get("type") == "lighting_scene_schedule"
                and proposal.get("status") == status):
            return pid, proposal
    return None


def _wait_for_lighting_proposal(
    client: HAClient,
    entity_id: str,
    timeout_s: int,
    poll_s: float,
) -> tuple[str, dict]:
    """Poll until a pending lighting_scene_schedule proposal appears."""
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        attrs = _proposals_attrs(client, entity_id)
        result = _find_lighting_proposal(attrs, "pending")
        if result is not None:
            return result
        time.sleep(poll_s)
    raise RuntimeError(
        f"Timeout: no pending lighting_scene_schedule proposal in {entity_id} after {timeout_s}s"
    )


class HAFlowClient(HAClient):
    def options_flow_init(self, entry_id: str) -> dict[str, Any]:
        data = self.post("/api/config/config_entries/options/flow", {"handler": entry_id})
        if not isinstance(data, dict):
            raise HAApiError(f"invalid options flow init response: {type(data)}")
        return data

    def options_flow_configure(self, flow_id: str, payload: dict[str, Any]) -> dict[str, Any]:
        data = self.post(f"/api/config/config_entries/options/flow/{flow_id}", payload)
        if not isinstance(data, dict):
            raise HAApiError(f"invalid options flow response: {type(data)}")
        return data

    def options_flow_abort(self, flow_id: str) -> None:
        self.delete(f"/api/config/config_entries/options/flow/{flow_id}")


def _menu_next(client: HAFlowClient, flow_id: str, next_step_id: str) -> dict[str, Any]:
    return client.options_flow_configure(flow_id, {"next_step_id": next_step_id})


def _expect_step(result: dict[str, Any], step_id: str) -> None:
    got = result.get("step_id")
    _assert(got == step_id, f"expected step_id={step_id!r}, got={got!r} — {result}")


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------

def step_reset_learning(client: HAClient, entry_id: str) -> None:
    print("  → learning_reset")
    client.call_service("heima", "command", {
        "command": "learning_reset",
        "target": {"entry_id": entry_id},
    })


def step_seed_events(
    client: HAClient,
    entry_id: str,
    light_entity: str,
    room_id: str,
    weekday: int,
    minute: int,
    brightness: int | None,
    color_temp_kelvin: int | None,
    count: int,
) -> None:
    print(f"  → seed_lighting_events: {count} eventi per {light_entity} (room={room_id} "
          f"weekday={weekday} minute={minute})")
    params: dict[str, Any] = {
        "entity_id": light_entity,
        "room_id": room_id,
        "weekday": weekday,
        "minute": minute,
        "count": count,
    }
    if brightness is not None:
        params["brightness"] = brightness
    if color_temp_kelvin is not None:
        params["color_temp_kelvin"] = color_temp_kelvin
    client.call_service("heima", "command", {
        "command": "seed_lighting_events",
        "target": {"entry_id": entry_id},
        "params": params,
    })


def step_verify_real_recording(
    client: HAClient,
    light_entity: str,
    event_store_entity: str,
    poll_s: float,
    timeout_s: int = 10,
) -> None:
    """Toggle the real light entity and verify LightingRecorderBehavior records the event.

    Requires:
    - The light entity to exist in HA
    - The corresponding room to have area_id set in Heima options (via recover_lighting_areas)
    - LightingRecorderBehavior to be subscribed to EVENT_STATE_CHANGED

    If the entity does not exist, the step is skipped with a warning.
    """
    if not client.entity_exists(light_entity):
        print(f"  → WARN: {light_entity} non trovata, skip verifica recording reale")
        return

    state_before = client.get_state(event_store_entity)
    attrs_before = state_before.get("attributes") or {}
    lighting_before = _to_int(attrs_before.get("lighting", 0))

    print(f"  → toggle {light_entity} per verificare LightingRecorderBehavior "
          f"(lighting events prima: {lighting_before})")

    # Turn on
    client.call_service("light", "turn_on", {"entity_id": light_entity})
    time.sleep(0.5)
    # Turn off
    client.call_service("light", "turn_off", {"entity_id": light_entity})

    # Poll for new lighting event
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        attrs = (client.get_state(event_store_entity).get("attributes") or {})
        lighting_after = _to_int(attrs.get("lighting", 0))
        if lighting_after > lighting_before:
            print(f"     OK: LightingRecorderBehavior ha registrato l'evento "
                  f"(lighting events: {lighting_before} → {lighting_after})")
            return
        time.sleep(poll_s)

    print(f"  → WARN: nessun nuovo lighting event in {timeout_s}s — "
          f"verificare che il room abbia area_id configurato e corrisponda all'area di {light_entity}")


def step_trigger_proposal_run(client: HAClient, entry_id: str) -> None:
    print("  → reload config entry → ProposalEngine.async_run()")
    client.call_service("homeassistant", "reload_config_entry", {"entry_id": entry_id})


def step_wait_for_proposal(
    client: HAClient,
    proposals_entity: str,
    timeout_s: int,
    poll_s: float,
) -> tuple[str, dict]:
    print(f"  → attesa proposta lighting_scene_schedule in {proposals_entity}")
    proposal_id, proposal = _wait_for_lighting_proposal(
        client, proposals_entity, timeout_s=timeout_s, poll_s=poll_s
    )
    conf = proposal.get("confidence", "?")
    desc = str(proposal.get("description", "")).strip()
    print(f"     proposta trovata: id={proposal_id} confidence={conf} desc={desc!r}")
    return proposal_id, proposal


def step_diag_check(client: HAClient, proposals_entity: str, proposal_id: str) -> None:
    """Verify proposal details via sensor attributes (equivalent to 030 diagnostic check)."""
    print("  → verifica diagnostica proposta (stile 030)")
    attrs = _proposals_attrs(client, proposals_entity)
    proposal = attrs.get(proposal_id)
    _assert(isinstance(proposal, dict), f"proposta {proposal_id} non trovata negli attributi")
    _assert(proposal.get("type") == "lighting_scene_schedule",
            f"tipo proposta errato: {proposal.get('type')}")
    _assert(proposal.get("status") == "pending",
            f"status atteso 'pending', trovato: {proposal.get('status')}")
    conf = float(proposal.get("confidence", 0))
    _assert(conf >= 0.3, f"confidence troppo bassa: {conf}")
    analyzer = str(proposal.get("analyzer_id", ""))
    _assert(analyzer == "LightingPatternAnalyzer",
            f"analyzer_id errato: {analyzer!r}")
    print(f"     OK: type={proposal.get('type')} status={proposal.get('status')} "
          f"confidence={conf:.2f} analyzer={analyzer}")


def step_accept_proposal(
    client: HAFlowClient,
    entry_id: str,
    proposals_entity: str,
    proposal_id: str,
) -> None:
    print(f"  → accettazione proposta {proposal_id} via options flow")
    init = client.options_flow_init(entry_id)
    flow_id = str(init["flow_id"])
    _expect_step(init, "init")

    step = _menu_next(client, flow_id, "reactions")
    _expect_step(step, "reactions")

    step = _menu_next(client, flow_id, "proposals")
    _expect_step(step, "proposals")

    result = client.options_flow_configure(flow_id, {
        "proposals_accept": [proposal_id],
        "proposals_reject": [],
    })
    if result.get("type") == "create_entry":
        return

    saved = _menu_next(client, flow_id, "save")
    _assert(saved.get("type") == "create_entry", f"expected create_entry, got: {saved}")


def step_verify_accepted(
    client: HAClient,
    proposals_entity: str,
    proposal_id: str,
    timeout_s: int,
    poll_s: float,
) -> None:
    print(f"  → verifica status=accepted per {proposal_id}")
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        attrs = _proposals_attrs(client, proposals_entity)
        proposal = attrs.get(proposal_id)
        if isinstance(proposal, dict) and proposal.get("status") == "accepted":
            print("     accepted confermato nel sensore")
            return
        time.sleep(poll_s)
    raise RuntimeError(f"Timeout: proposta {proposal_id} non accepted dopo {timeout_s}s")


def step_verify_other_proposals_intact(
    client: HAClient,
    proposals_entity: str,
    other_types: list[str],
) -> None:
    """Verify that proposals of other types (e.g. presence_preheat) were not destroyed."""
    if not other_types:
        return
    print(f"  → verifica che le proposte di tipo {other_types} siano intatte")
    attrs = _proposals_attrs(client, proposals_entity)
    for ptype in other_types:
        found = any(
            isinstance(p, dict) and p.get("type") == ptype
            for p in attrs.values()
        )
        if found:
            print(f"     OK: proposte '{ptype}' ancora presenti")
        else:
            print(f"     WARN: nessuna proposta '{ptype}' trovata (potrebbe non essere stata generata)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description="Heima lighting-schedule live E2E test (P9)")
    parser.add_argument("--ha-url", default="http://127.0.0.1:8123")
    parser.add_argument("--ha-token", required=True)
    parser.add_argument("--light-entity", default="light.test_heima_living_main",
                        help="HA entity_id della luce (default: test lab living)")
    parser.add_argument("--room-id", default="living", help="Heima room_id (default: living)")
    parser.add_argument("--weekday", type=int, default=0, help="0=Lun … 6=Dom")
    parser.add_argument("--minute", type=int, default=1200,
                        help="minuto del giorno (0-1439); default 1200=20:00")
    parser.add_argument("--brightness", type=int, default=None)
    parser.add_argument("--color-temp-kelvin", type=int, default=None)
    parser.add_argument("--event-count", type=int, default=6,
                        help="eventi sintetici da iniettare (min 5)")
    parser.add_argument("--timeout-s", type=int, default=60)
    parser.add_argument("--poll-s", type=float, default=1.0)
    parser.add_argument("--reset", action="store_true",
                        help="esegui learning_reset prima del seeding (distrugge proposte precedenti)")
    parser.add_argument("--skip-accept", action="store_true",
                        help="salta lo step di accettazione proposta")
    args = parser.parse_args()

    if args.event_count < 5:
        print("FAIL: --event-count deve essere >= 5 (gate analyzer)", file=sys.stderr)
        return 1

    client = HAFlowClient(base_url=args.ha_url, token=args.ha_token)
    proposals_entity = "sensor.heima_reaction_proposals"

    entry_id = client.find_heima_entry_id()
    print(f"Heima entry_id={entry_id}")

    count_before = _to_int(client.get_state(proposals_entity).get("state"))
    print(f"Proposte esistenti prima del test: {count_before}")

    # 1. Reset (opzionale)
    if args.reset:
        step_reset_learning(client, entry_id)
    else:
        print("  → learning_reset saltato (usa --reset per azzerare)")

    # 2. Verifica recording reale: toggle della luce vera e verifica che
    #    LightingRecorderBehavior catturi l'evento via STATE_CHANGED
    #    (funziona solo se il room ha area_id configurato via recover_lighting_areas)
    step_verify_real_recording(
        client,
        light_entity=args.light_entity,
        event_store_entity="sensor.heima_event_store",
        poll_s=args.poll_s,
    )

    # 3. Seed eventi sintetici (per superare il gate _spans_min_weeks)
    step_seed_events(
        client,
        entry_id,
        light_entity=args.light_entity,
        room_id=args.room_id,
        weekday=args.weekday,
        minute=args.minute,
        brightness=args.brightness,
        color_temp_kelvin=args.color_temp_kelvin,
        count=args.event_count,
    )

    # 4. Trigger proposal run
    step_trigger_proposal_run(client, entry_id)

    # 5. Attesa proposta lighting
    proposal_id, proposal = step_wait_for_proposal(
        client, proposals_entity, timeout_s=args.timeout_s, poll_s=args.poll_s
    )

    # 6. Verifica diagnostica (stile 030)
    step_diag_check(client, proposals_entity, proposal_id)

    if not args.reset:
        # Verifica che le proposte di altri tipi non siano state distrutte
        step_verify_other_proposals_intact(client, proposals_entity, ["presence_preheat"])

    if args.skip_accept:
        print("PASS: proposta lighting generata e verificata (accept saltato)")
        return 0

    # 7. Accetta proposta
    step_accept_proposal(client, entry_id, proposals_entity, proposal_id)

    # 8. Verifica accepted
    step_verify_accepted(client, proposals_entity, proposal_id,
                         timeout_s=30, poll_s=args.poll_s)

    print("PASS: lighting schedule E2E pipeline completa")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # noqa: BLE001
        print(f"FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)
